## Importing the libraries

In [1]:
## importing important libraries
import wikipedia
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Checking the validity of the query

In [2]:
## This function is written to check the validity of the query, i.e., if this query is a valid movie query or not.
## It is assumed that every movie query has a plot section in it.
def link_check(name):
    try:
        film_page = wikipedia.page('{}'.format(name))
        film_plot = film_page.section('Plot')
        if film_plot == None:
            return False
        else:
            return True
    except:
        return False

In [3]:
## This block can be used to check if any query is a valid movie query or not.
## This block is for debugging purpose.
film_check = link_check('the battle of algiers 1967 film')
print(film_check)

False

## Data Extraction

In [4]:
## This block will will fetch us the data for a valid movie query

def film_data_process(film):
    '''
    Returned data will be in a list which will have four features as asked i.e. Movie title,Released date, Star cast and plot 

    '''
    ## As the sanctity of the movie query is already tested, so we are initiating the release date and star cast variable
    film_release = ' '
    film_cast = ' '
    film_page = wikipedia.page('{}'.format(film))
    film_title = film_page.title
    film_url = film_page.url
    film_df = pd.read_html('{}'.format(film_url))
    ## Below line will fetch info box of the wikipedia page from which we will fetch us the star cast and release date 
    film_info = film_df[0]
    col = film_info.columns
    for i in range(len(film_info)):
        if film_info[col[0]].iloc[i] == 'Starring':
            film_cast = film_info[col[1]].iloc[i]
        elif film_info[col[0]].iloc[i] == 'Release date':
            film_release = film_info[col[1]].iloc[i]
        else:
            continue

    film_plot = film_page.section('Plot')
    film_data_list = [film_title,film_release,film_cast,film_plot]
            
    return film_data_list

Star cast can also be extracted from the cast section of the page. But will raise another network query and will slow down the program.

In [5]:
## This code block is written for debugging purpose to fetch the data for a single query.
data = film_data_process('All About Eve 1950 film')
for i in data:
    print(i)
    print(type(i))
print(type(data))

All About Eve
<class 'str'>
October 13, 1950
<class 'str'>
Bette Davis Anne Baxter George Sanders Celeste Holm
<class 'str'>
Margo Channing (Bette Davis) is one of the biggest stars on Broadway. But having just turned forty she is worried about what her advancing age will mean for her career. After a performance of Margo's latest play, Aged in Wood, Margo's close friend Karen Richards (Celeste Holm), wife of the play's author Lloyd Richards (Hugh Marlowe), brings in a besotted fan, Eve Harrington (Anne Baxter), to meet Margo. Eve tells the group gathered in Margo's dressing room—Karen, Lloyd, Margo's boyfriend Bill Sampson (Gary Merrill), a director who is eight years her junior, and Margo's maid Birdie (Thelma Ritter)—that she followed Margo's last theatrical tour to New York City after seeing her perform in San Francisco. She tells an engrossing story of growing up poor in Wisconsin and losing her young husband Eddie in the South Pacific during World War II. Moved, Margo quickly befriends Eve, takes her into her home, and hires her as her assistant, leaving Birdie, who instinctively dislikes Eve, feeling put out.

Eve quickly manipulates her way into Margo's life, acting as her secretary and adoring fan. She seems to anticipate Margo's every need, including placing a long-distance phone call to Bill when Margo forgets his birthday. Margo becomes increasingly distrustful and bitter towards her, particularly after she catches Eve taking a bow to an empty theatre while pretending to wear Margo's costume for Aged in Wood. Margo asks her producer, Max Fabian, to hire Eve at his office, but instead Eve manages to become Margo's understudy without Margo's knowledge. As Margo's irritation grows, Karen feels sorry for Eve. In hopes of humbling Margo, Karen arranges for her to miss a performance of Aged in Wood, so Eve will have to give the performance in her place. Eve invites the city's theatre critics, including the acerbic Addison DeWitt (George Sanders), to attend that evening's performance, which is a triumph for her. After that evening's performance, Eve tries to seduce Bill, but he rejects her. Instead, Addison takes her under his wing and interviews her for a column that criticizes Margo for not making way for new talents like Eve. Margo and Karen are furious.
That evening, Margo and Bill announce their engagement at dinner with the Richardses in the Cub Room of the Stork Club. Eve, who was dining at a nearby table with DeWitt, calls Karen into the ladies' room and, after first appearing regretful, tells her to either ask Lloyd to give her the part of Cora—the lead in Lloyd's next play, Footsteps on the Ceiling—or she will reveal Karen's role in Margo's missed performance. Before Karen can talk with Lloyd, Margo announces to everyone's surprise that she does not wish to play Cora and would prefer to continue in Aged in Wood.
Eve is cast as Cora. Just before the out-of-town premiere of Footsteps on the Ceiling at the Shubert in New Haven, Eve presents Addison with her next plan: to marry Lloyd, who, she claims, has come to her professing his love and his eagerness to leave his wife for her. Now, Eve exults, Lloyd will write brilliant plays showcasing her. Angered that Eve believes she can manipulate him as easily as she does everyone else, Addison reveals he knows that her back story is all lies. Her real name is Gertrude Slescynski, she was never married, and she had been paid to leave town over an affair with her boss. Addison blackmails Eve, informing her that she will not be marrying Lloyd or anyone else; in exchange for Addison's silence, she now 'belongs' to him.
Several months later, Eve is a shining Broadway star headed for Hollywood. At an awards banquet, she thanks Margo, Bill, Lloyd, and Karen with characteristic effusion, while all four stare back at her coldly. Eve skips a party in her honor, and returns home alone, where she encounters Phoebe (Barbara Bates)—a high-school-aged fan—who has slipped into her apartment and fallen asleep. The young girl professes her adoration and begins at once to insinuate herself into Eve's life, offering to pack Eve's trunk for Hollywood. While Eve rests in the other room, Phoebe dons the elegant robe that Eve wore to the banquet and poses in front of a multi-paned mirror, holding the award as if it were a crown.
<class 'str'>
<class 'list'>

## Construction of list of the movies

Top  1000 movies of all time are taken from the link http://www.films101.com/t1000r.htm

In [6]:
## Construction of a dataframe from the given website

movies_list_df_1 = pd.read_html('http://www.films101.com/t1000r.htm')
movies_list_df_2 = pd.read_html('http://www.films101.com/t1000r2.htm')
movies_list_df_3 = pd.read_html('http://www.films101.com/t1000r3.htm')

In [7]:

## This function will return the movie list from the df passed in a list format.
## This function will vary based on the nature of the dataframe passed.

def list_construction(mov_list):
    movie_list = []
    len_list = len(mov_list)
    ## i represents every alternate odd column of the dataframe consists the desired list whose entries are also dataframe.
    for i in range(1,len_list,2):
        ## 1st column represnts the movie name
        ## 2nd column represnts the release year
        ## j represents the row.
        for j in range(len(mov_list[i])):
            name = mov_list[i][1][j] + ' ' + str(mov_list[i][2][j]) +' film'
            movie_list.append(name)
    return movie_list

In [8]:
## converting the dataframe into the list of movies contained in that page.
list_movie_1  = list_construction(movies_list_df_1)
list_movie_2  = list_construction(movies_list_df_2)
list_movie_3  = list_construction(movies_list_df_3)

In [9]:
## function of appending the each entry of movie list passed to form a single list rather than list of list
list_movie = []
def movie_append(mov_list):
    for i in range(len(mov_list)):
        list_movie.append(mov_list[i])

In [10]:
movie_append(list_movie_1)
movie_append(list_movie_2)
movie_append(list_movie_3)

In [11]:
len(list_movie)

1105

In [12]:
## for debugging purpose
## This will fetch us the list of the index and the movie name at that index for any given range(can be used to print complete movie range)
## This will also help us to get the final movie list with valid movie query
ind = 0
for i in range(10):
    if link_check(list_movie[i]):
        ind = ind + 1
        print('The film "{}" has index:{}'.format(list_movie[i],ind))
    else:
        continue

The film "Citizen Kane 1941 film" has index:1
The film "2001: A Space Odyssey 1968 film" has index:2
The film "The Rules of the Game 1939 film" has index:3
The film "Bicycle Thieves 1948 film" has index:4
The film "Vertigo 1958 film" has index:5
The film "The Godfather 1972 film" has index:6
The film "Seven Samurai 1954 film" has index:7
The film "Psycho 1960 film" has index:8
The film "Singin' in the Rain 1952 film" has index:9
The film "The Searchers 1956 film" has index:10

In [13]:
## Construction of the film_df with all the desired features
film_df = pd.DataFrame(data=None, columns='Movie_Title Release_date Movie_cast Movie_plot'.split())
for i in range(len(list_movie)):
    print(i) ## To track the progress
    if link_check('{}'.format(list_movie[i])):
        film_data_cache = film_data_process('{}'.format(list_movie[i]))
        film_df_2 = pd.DataFrame(data = [film_data_cache], columns='Movie_Title Release_date Movie_cast Movie_plot'.split())
        film_df = pd.concat([film_df,film_df_2]) 
    else:
        continue

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103

c:\Miniconda\envs\py37_default\lib\site-packages\wikipedia\wikipedia.py:389: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 389 of the file c:\Miniconda\envs\py37_default\lib\site-packages\wikipedia\wikipedia.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  lis = BeautifulSoup(html).find_all('li')

104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104

In [14]:
film_df.head()

,Movie_Title,Release_date,Movie_cast,Movie_plot
0,Citizen Kane,"May 1, 1941Palace Theatre) September 5, 1941",Orson Welles Joseph Cotten Dorothy Comingore E...,"In a mansion called Xanadu, part of a vast pal..."
0,2001: A Space Odyssey (film),2 April 1968Uptown Theater) 3 April 1968 15 Ma...,Keir Dullea Gary Lockwood,"In the prehistoric African veldt, a tribe of h..."
0,The Rules of the Game,7 July 1939 (Paris),Nora GregorPaulette DubostMarcel DalioRoland T...,Aviator André Jurieux (Roland Toutain) lands a...
0,Bicycle Thieves,24 November 1948,Enzo Staiola Lamberto Maggiorani,In the post-World War II Val Melaina neighbour...
0,Vertigo (film),"May 9, 1958",James Stewart Kim Novak Barbara Bel Geddes Tom...,"After a rooftop chase, where a fellow policema..."

In [15]:
film_df.reset_index(drop = True, inplace = True)
film_df.head()

,Movie_Title,Release_date,Movie_cast,Movie_plot
0,Citizen Kane,"May 1, 1941Palace Theatre) September 5, 1941",Orson Welles Joseph Cotten Dorothy Comingore E...,"In a mansion called Xanadu, part of a vast pal..."
1,2001: A Space Odyssey (film),2 April 1968Uptown Theater) 3 April 1968 15 Ma...,Keir Dullea Gary Lockwood,"In the prehistoric African veldt, a tribe of h..."
2,The Rules of the Game,7 July 1939 (Paris),Nora GregorPaulette DubostMarcel DalioRoland T...,Aviator André Jurieux (Roland Toutain) lands a...
3,Bicycle Thieves,24 November 1948,Enzo Staiola Lamberto Maggiorani,In the post-World War II Val Melaina neighbour...
4,Vertigo (film),"May 9, 1958",James Stewart Kim Novak Barbara Bel Geddes Tom...,"After a rooftop chase, where a fellow policema..."

In [16]:
film_df.to_csv('test_data.csv')